# Generated by Django 4.1.13 on 2024-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
