# Generated by Django 4.1.13 on 2024-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='id',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
